# Generated by Django 5.2 on 2026-09-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_root',
            field=models.BooleanField(db_index=True, default=False, help_text='根管理员可以管理系统角色和权限', verbose_name='是否为根管理员'),
        ),
    ]
