# Generated by Django 5.2 on 2026-09-15 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userrole_user_roles_userrole_idx_user_role_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role', verbose_name='角色'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
