# Generated by Django 5.2 on 2026-09-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_roles_user_role_delete_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=1, help_text='版本变化后，之前签发的Token立即失效', verbose_name='Token版本'),
        ),
    ]
