# Generated by Django 5.2 on 2026-09-16 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_user_token_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='页面名称')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='页面编码')),
                ('path', models.CharField(max_length=255, unique=True, verbose_name='页面路由')),
                ('component', models.CharField(blank=True, default='', max_length=255, verbose_name='前端组件')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='页面图标')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='pages.page', verbose_name='父页面')),
                ('visible_roles', models.ManyToManyField(blank=True, db_table='sys_page_roles', related_name='pages', to='users.role', verbose_name='可见角色')),
            ],
            options={
                'verbose_name': '系统页面',
                'verbose_name_plural': '系统页面',
                'db_table': 'sys_pages',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
